# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/astrapay
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Redis Configuration
spring.data.redis.host=localhost
spring.data.redis.port=6379

# Virtual Threads (Project Loom)
spring.threads.virtual.enabled=true

# Application Properties
server.port=8081

# Kafka Configuration
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.group-id=astra-pay-group
spring.kafka.consumer.properties.spring.json.trusted.packages=com.astrapay.*

# JWT Configuration
astrapay.jwt.secret=5367566B58703273357638792F423F4428472B4B6250655368566D5971337436
astrapay.jwt.expiration=86400000

# Razorpay Configuration
razorpay.key.id=rzp_test_SLE7mvITAOsDDj
razorpay.key.secret=4zzRbdE0kA7ntQtVIMOJQOix

